"""add activity name

Revision ID: 31e0662aaddb
Revises: add6995b6f20
Create Date: 2026-04-04 12:53:43.662443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31e0662aaddb'
down_revision: Union[str, Sequence[str], None] = 'add6995b6f20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('activity_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'activity_name')
    # ### end Alembic commands ###
