"""add daily steps table

Revision ID: 967e074facc0
Revises: cb649e4a25bf
Create Date: 2026-03-24 23:10:34.501096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '967e074facc0'
down_revision: Union[str, Sequence[str], None] = 'cb649e4a25bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date')
    )
    op.create_index(op.f('ix_daily_steps_id'), 'daily_steps', ['id'], unique=False)
    op.create_index(op.f('ix_daily_steps_user_id'), 'daily_steps', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_steps_user_id'), table_name='daily_steps')
    op.drop_index(op.f('ix_daily_steps_id'), table_name='daily_steps')
    op.drop_table('daily_steps')
    # ### end Alembic commands ###
